// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyckasxuqvgoyanvmgzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Y2thc3h1cXZnb3lhbnZtZ3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Mjc2NjIsImV4cCI6MjA1OTEwMzY2Mn0.oidABVmLQW4Lm9ZidKPe672coROw9sjICUH3PjuJifA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);